language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ozgursastim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ozgursastim/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-434222498441"
  bucket_path: "docker"
  on:
    branch: master
    