language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ozgursastim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ozgursastim/docker-react npm run test -- --coverage
